name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with: 
        node-version: '14'
    # Check if change files are created 
    - run: node common/scripts/install-run-rush.js change -v
    - run: node common/scripts/install-run-rush.js install --bypass-policy
    - run: node common/scripts/install-run-rush.js rebuild --bypass-policy --verbose